### ISSUE TITLE
Broken download link

### ISSUE THREAD

**Issue by 442623641** [crosswalk-project/cordova-plugin-crosswalk-webview#163] opened 2017-09-03 10:10 UTC
Failed to list versions for org.xwalk:xwalk_core_library.
> Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
> Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

**Comment by bellalMohamed** [comment] 2017-09-03 12:18
The same problem here, wish it's just a temporary one.

**Comment by bellalMohamed** [comment] 2017-09-03 12:20
I think they stopped debugging and developing the project, it'd be a catastrophe if they didn't update the link -_-

**Comment by YissacharB** [comment] 2017-09-03 17:06
Any update?

**Comment by renatobezerra** [comment] 2017-09-04 01:18
Hi everyone. I have a same issue. I can't build my application because it.

**Comment by 442623641** [comment] 2017-09-04 01:38
I hope it can be fixed asap

**Comment by seagomezar** [comment] 2017-09-04 02:12
Same problem, link broken.

**Comment by renatobezerra** [comment] 2017-09-04 02:28
Hi people. I found a possible solution for this issue.
https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/158

Search the @RicardoBer comment's of 2 days ago.

**Comment by 442623641** [comment] 2017-09-04 03:17
yes，a possible solution for this issue @RicarddoBer  comment's of 2 days ago.

**Comment by johann04** [comment] 2017-09-04 04:13
any solution or workaround?

**Comment by renatobezerra** [comment] 2017-09-04 04:15
@johann04 Sorry. It's workaround. But solved for me.

**Comment by zhouzhongyuan** [comment] 2017-09-04 06:43
You can use this plugin temporarily:
```
cordova plugin add https://github.com/zhouzhongyuan/cordova-plugin-crosswalk-webview
```
It just fixed this error.

**Comment by rakuco** [comment] 2017-09-04 09:31
I'm marking this as a duplicate of #158 to centralize everything in a single place.

**Closed by rakuco** 2017-09-04 09:31 UTC
