### ISSUE TITLE
Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

### ISSUE THREAD

**Issue by cnhj352** [crosswalk-project/cordova-plugin-crosswalk-webview#164] opened 2017-09-05 02:00 UTC
> Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable

what is problem？

**Comment by cnhj352** [comment] 2017-09-05 02:01
i use ionic 【cordova build android --release】 and then ...

**Comment by jmevangelist** [comment] 2017-09-05 02:28
Noticed that even https://download.01.org/crosswalk/releases/crosswalk/ is not accessible too.

**Comment by jmevangelist** [comment] 2017-09-05 02:33
relate to #158

**Comment by jmevangelist** [comment] 2017-09-05 05:45
(for version 23) solved by editing the config file and adding:
`<preference name="xwalkVersion" value="xwalk_core_library:23.53.589.4" />` 

for other versions, if you already have an existing apk you can check the crosswalk version by using chrome inspect and typing in navigator.userAgent.

**Comment by rakuco** [comment] 2017-09-05 07:48
Closing as a duplicate of #158. See also: https://lists.crosswalk-project.org/pipermail/crosswalk-help/2017-September/002465.html

**Closed by rakuco** 2017-09-05 07:48 UTC
