### ISSUE TITLE
An error occurred while processing your request.

### ISSUE THREAD

**Issue by xiaolongyuan** [crosswalk-project/cordova-plugin-crosswalk-webview#162] opened 2017-09-02 16:40 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
   > Could not resolve org.xwalk:xwalk_core_library:23+.
     Required by:
         project :
      > Could not resolve org.xwalk:xwalk_core_library:23+.
         > Failed to list versions for org.xwalk:xwalk_core_library.
            > Unable to load Maven meta-data from https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
               > Could not GET 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. Received status code 503 from server: Service Unavailable
```

https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml
An error occurred while processing your request.
Reference #30.7e6f33f.1504370378.8f5c911

**Comment by bludnic** [comment] 2017-09-02 22:56
same issue

**Comment by dieckie** [comment] 2017-09-02 23:11
I had the same problem, but this project seems to be discontinued; #158 describes the same issue and found the answer helpful.

**Comment by xiaohui-zhangxh** [comment] 2017-09-04 06:46
put below code to config.yml of cordova project:

     <preference name="xwalkVersion" value="xwalk_core_library:23.53.589.4" />

**Comment by rakuco** [comment] 2017-09-04 09:30
I'm marking this as a duplicate of #158 to centralize everything in a single place.

**Closed by rakuco** 2017-09-04 09:30 UTC
